### ISSUE TITLE
提示输入文字回车后  Expression expected.

### ISSUE THREAD

**Issue by bymori** [ren-wei/echarts-enhanced-completion#1]
您好 在使用中目前发现输入bottom  left top等值时候 回车键入了 `top: 0%,`  在html页面引入js使用中 需要  `top: 0 ,`   或者top: ’‘ , 添加引号才可以
不知道是否哪里配置问题呢 感谢
![Snipaste_2021-09-30_18-14-46](https://gitee.com/bymori/pic-go-core/raw/master/img/Snipaste_2021-09-30_18-14-46.png)
图片url地址 https://gitee.com/bymori/pic-go-core/raw/master/img/Snipaste_2021-09-30_18-14-46.png

**Comment by ren-wei** [comment]
非常感谢您的反馈，已经确认这是一个bug，我将会在下一个版本(`v1.2.2`)中修复此问题。
