### ISSUE TITLE
[Feature] 是否可以支持不同的版本选择呢？

### ISSUE THREAD

**Issue by cMing1997** [ren-wei/echarts-enhanced-completion#4]
### What problem does this feature solve?

 不同的 `echarts` 版本之间，其实还是有很多特性不一样的，有的特性在老的版本里没有，新的版本里设置了默认。作者这的根据`echarts` 的官方文档来，是否支持多版本的呢？默认是支持最新版本，但是可以配置为 `echarts` 的某一个版本

**Comment by ren-wei** [comment]
暂定 1.6 版本支持，正在考虑实现方案：

**Comment by ren-wei** [comment]
`v1.6.0` 已发布，由于文档来源于 [echarts-doc](https://github.com/apache/echarts-doc) 项目，所以我只能支持`master`分支(最新版)和 `v4 `分支(v4.x) 两个版本。
通过配置进行选择其中一个版本。
