### ISSUE TITLE
[Bug] 这个库有有安全风险

### ISSUE THREAD

**Issue by cMing1997** [ren-wei/echarts-enhanced-completion#5]
### Version

随意指定

### File type

javascript

### Steps to Reproduce

无

### Current Behavior

无

### Expected Behavior

无

### Environment

```markdown
- **OS**:
```

### Any additional comments?

我不太清楚作者有没有收到，我这提了一个feature之后，给我发了一个邮件
![image](https://user-images.githubusercontent.com/40878104/186809795-bd3ed1eb-6df2-40d6-b206-7f4186259b86.png)
![image](https://user-images.githubusercontent.com/40878104/186809906-ad066942-a068-4fc4-b4cd-a30b3db7ff04.png)

**完整报告:** [https://www.oscs1024.com/cd/1530680751505514496?sign=55f88a82&report=1](https://sctrack.sendcloud.net/track/click/eyJuZXRlYXNlIjogImZhbHNlIiwgIm1haWxsaXN0X2lkIjogMCwgInRhc2tfaWQiOiAiIiwgImVtYWlsX2lkIjogIjE2NjE0ODMxMTE5NzRfMTYwNzcwXzEyMjc4OV82ODU5LnNjLTEwXzlfMTJfMjA2LWluYm91bmQwJDE4NTA4MjM3NjZAcXEuY29tIiwgInNpZ24iOiAiMWM1MTk1YWIzOWIzYWQ4MDI3YzE4ZWNmZGNjNzdlZmMiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIyMjMxNDA2MSIsICJ0cmFja19kb21haW4iOiAic2N0cmFjay5zZW5kY2xvdWQubmV0IiwgInJlYWxfdHlwZSI6ICIiLCAibGluayI6ICJodHRwcyUzQS8vd3d3Lm9zY3MxMDI0LmNvbS9jZC8xNTMwNjgwNzUxNTA1NTE0NDk2JTNGc2lnbiUzRDU1Zjg4YTgyJTI2cmVwb3J0JTNEMSIsICJvdXRfaXAiOiAiMTE3LjUwLjY2LjEyIiwgImNvbnRlbnRfdHlwZSI6IDMsICJ1c2VyX2lkIjogMTYwNzcwLCAib3ZlcnNlYXMiOiAiZmFsc2UiLCAiY2F0ZWdvcnlfaWQiOiAyNTczNDd9.html)

**漏洞一：** nanoid@3.1.20 - 间接引入
**影响描述：** nanoid是用于 JavaScript 的小型、安全、URL 友好、唯一的字符串 ID 生成器。nanoid安全中存在漏洞，该漏洞源于nanoid 容易通过 valueOf() 函数受到信息暴露的影响，该函数允许重现最后生成的 id。
**漏洞详情：** [https://www.oscs1024.com/hd/MPS-2021-19605](https://sctrack.sendcloud.net/track/click/eyJuZXRlYXNlIjogImZhbHNlIiwgIm1haWxsaXN0X2lkIjogMCwgInRhc2tfaWQiOiAiIiwgImVtYWlsX2lkIjogIjE2NjE0ODMxMTE5NzRfMTYwNzcwXzEyMjc4OV82ODU5LnNjLTEwXzlfMTJfMjA2LWluYm91bmQwJDE4NTA4MjM3NjZAcXEuY29tIiwgInNpZ24iOiAiMGQ3NWIyOWYzYTMyZjU3NWFhZTVlYTYwNjg2ZDhiZTkiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIyMjMxNDA2MSIsICJ0cmFja19kb21haW4iOiAic2N0cmFjay5zZW5kY2xvdWQubmV0IiwgInJlYWxfdHlwZSI6ICIiLCAibGluayI6ICJodHRwcyUzQS8vd3d3Lm9zY3MxMDI0LmNvbS9oZC9NUFMtMjAyMS0xOTYwNSUzRnMlM0RtIiwgIm91dF9pcCI6ICIxMTcuNTAuNjYuMTIiLCAiY29udGVudF90eXBlIjogMywgInVzZXJfaWQiOiAxNjA3NzAsICJvdmVyc2VhcyI6ICJmYWxzZSIsICJjYXRlZ29yeV9pZCI6IDI1NzM0N30=.html)

**漏洞二：**  follow-redirects@1.14.7 - 间接引入
**影响描述：** Exposure of Sensitive Information to an Unauthorized Actor in NPM follow-redirects prior to 1.14.8.
**漏洞详情：** [https://www.oscs1024.com/hd/MPS-2022-3636](https://sctrack.sendcloud.net/track/click/eyJuZXRlYXNlIjogImZhbHNlIiwgIm1haWxsaXN0X2lkIjogMCwgInRhc2tfaWQiOiAiIiwgImVtYWlsX2lkIjogIjE2NjE0ODMxMTE5NzRfMTYwNzcwXzEyMjc4OV82ODU5LnNjLTEwXzlfMTJfMjA2LWluYm91bmQwJDE4NTA4MjM3NjZAcXEuY29tIiwgInNpZ24iOiAiN2Y2ZjdlODY4YWVjZTc5MGNlNjk3M2QxODMxODJmY2MiLCAidXNlcl9oZWFkZXJzIjoge30sICJsYWJlbCI6ICIyMjMxNDA2MSIsICJ0cmFja19kb21haW4iOiAic2N0cmFjay5zZW5kY2xvdWQubmV0IiwgInJlYWxfdHlwZSI6ICIiLCAibGluayI6ICJodHRwcyUzQS8vd3d3Lm9zY3MxMDI0LmNvbS9oZC9NUFMtMjAyMi0zNjM2JTNGcyUzRG0iLCAib3V0X2lwIjogIjExNy41MC42Ni4xMiIsICJjb250ZW50X3R5cGUiOiAzLCAidXNlcl9pZCI6IDE2MDc3MCwgIm92ZXJzZWFzIjogImZhbHNlIiwgImNhdGVnb3J5X2lkIjogMjU3MzQ3fQ==.html)

**Comment by ren-wei** [comment]
有收到，我会在下一个版本更新一下依赖

**Comment by ren-wei** [comment]
1.5.5 已更新
