### ISSUE TITLE
语言方面加一个php支持吧 辛苦大佬了 😉

### ISSUE THREAD

**Issue by GladioFeng** [ren-wei/echarts-enhanced-completion#6]
### What problem does this feature solve?

thank you, my load

**Comment by ren-wei** [comment]
ok

**Comment by ren-wei** [comment]
`v1.6.0` 已发布，已支持php。

**Comment by GladioFeng** [comment]
666 👍🏻👍🏿👍🏽👍
________________________________
发件人: ren-wei ***@***.***>
发送时间: Wednesday, September 28, 2022 11:04:48 PM
收件人: ren-wei/echarts-enhanced-completion ***@***.***>
抄送: GladioFeng ***@***.***>; Author ***@***.***>
主题: Re: [ren-wei/echarts-enhanced-completion] 语言方面加一个php支持吧 辛苦大佬了 😉 (Issue #6)


v1.6.0 已发布，已支持php。
