### ISSUE TITLE
是否考虑扩展tsx和jsx？

### ISSUE THREAD

**Issue by CaptainJon** [ren-wei/echarts-enhanced-completion#8]
### What problem does this feature solve?

如题，目前基本都是组件化开发了，jsx和tsx很常见了

**Comment by ren-wei** [comment]
感谢您的反馈，我会在下一个版本(**1.6.4**)加上对 jsx 和 tsx 的支持，但是目前使用的解析引擎是 **esprima** ，因此对 jsx 和 tsx 只能部分支持。
