### ISSUE TITLE
将回车键触发提示的功能做成可以配置的

### ISSUE THREAD

**Issue by ruan-cat** [ren-wei/echarts-enhanced-completion#9]
### What problem does this feature solve?

期望将回车键触发提示的功能做成可以配置的，每次回车的时候都不停地触发提示，很影响开发。希望把这个触发提示的功能做成可以配置的，比如填写false就是关闭。

**Comment by ren-wei** [comment]
感谢您的反馈，我会在下一个版本(1.6.5)将回车键触发提示的功能做成可以配置的。

**Comment by ren-wei** [comment]
v1.6.5 已发布，您可以在更新后，在设置中搜索 `echarts-enhanced-completion.completion.disableEnterTriggerCharacters` 然后勾选 `禁用 Enter 触发补全`。
**注意：** 设置完成后您需要重启您的 vscode 以使设置生效。
